trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - azure-pipelines.yml
      - src/*
      - "*.md"
      - .vscode/*

# Disables triggering Pipeline run at creation of every Pull Request
pr: none

pool:
  vmImage: "ubuntu-latest"

resources:
  containers:
    - container: prime_pipeline_container
      image: dfdsdk/prime-pipeline:0.6.14
      env:
        TF_VAR_my_secret_token: $(TF_VAR_my_secret_token) # Example of defining an environment variable that can be passed to terraform
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID),
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

variables:
  - group: samdi-creds-group

stages:
- stage: Dev
  condition: eq(variables['Build.Reason'], 'PullRequest')
  variables:
    environment: sandbox
  jobs:
  - job: terraform_dev_apply
    displayName: Dev apply
    container: prime_pipeline_container
    steps:
    - script: |
        terragrunt plan --terragrunt-working-dir infrastructure/environments/dev --terragrunt-source-update --terragrunt-non-interactive -input=false
        # terragrunt apply-all --terragrunt-source-update --terragrunt-non-interactive -input=false -auto-approve
      displayName: Terragrunt Apply
  - job: terraform_prod_plan
    displayName: Prod Plan
    container: prime_pipeline_container
    steps:
    - script: |
        terragrunt plan --terragrunt-working-dir infrastructure/environments/prod --terragrunt-source-update --terragrunt-non-interactive -input=false
      displayName: Terragrunt Plan


- stage: Prod
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main') # Trigger this after merge to main branch
  jobs:
  - job: terraform_prod_apply
    displayName: Prod Apply
    container: prime_pipeline_container
    steps:
    - script: |
        terragrunt plan --terragrunt-working-dir infrastructure/environments/prod --terragrunt-source-update --terragrunt-non-interactive -input=false
        # terragrunt apply-all --terragrunt-source-update --terragrunt-non-interactive -input=false -auto-approve
      displayName: Terragrunt Apply

